server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 250MB
      max-request-size: 250MB

cloud:
  aws:
    credentials:
      access-key: AKIAXYKJWPCTHHOSOJNB
      secret-key: 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
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: budzisz3
